name: Acorn CI
on:
  push:
    branches: [ "main", "youngjoven", "dev" ]
    paths:
    - 'getmem/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cd getmem && docker build -t youngjoven/getmem .
    - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - run: docker push youngjoven/getmem
